# Generated by Django 5.2.7 on 2025-10-15 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('cod_post', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('biogradia', models.TextField(blank=True, null=True)),
                ('exp_laboral', models.TextField(blank=True, null=True)),
                ('educacion', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('best_work', models.TextField(blank=True, null=True)),
                ('last_work', models.TextField(blank=True, null=True)),
                ('nivel_experiencia', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
