# Generated by Django 5.2.7 on 2025-10-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=200)),
                ('descripcion_vacante', models.CharField(max_length=300)),
                ('salario', models.IntegerField()),
                ('prestaciones', models.CharField(max_length=400)),
                ('requisitos', models.CharField(max_length=400)),
            ],
        ),
    ]
