# Generated by Django 5.2.7 on 2025-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_vacante_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
