# Generated by Django 5.2.7 on 2025-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_vacante_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='postulaciones',
            field=models.IntegerField(default=0),
        ),
    ]
